### ISSUE TITLE
Doesn't work with python3.5

### ISSUE THREAD

**Issue by zloidemon** [plugaai/aioinflux#1]
Actually i don't see reason to use that library without support python 3.5. Not all LTS linux distros provide python3.6.

**Comment by gusutabopb** [comment]
You are not forced to use the Python that shipped with your OS. Actually, it's really bad practice messing up with your OS Python installation. I personally recommend you checkout conda/Miniconda and install a Python distribution for your application on userland. There's also Docker and probably many other alternatives to using the Python shipped with your OS.

I use aioinflux as part of a larger application that depends on some Python 3.6 only functionality. I have no plans of supporting 3.5, but in case you want to fork it and make your own version, for aioinflux, most modifications should be rather trivial (basically removing f-strings).
