### ISSUE TITLE
UDP inserts?

### ISSUE THREAD

**Issue by vgoklani** [plugaai/aioinflux#12]
Thanks for creating this library? Does it support UDP inserts via asyncio?

i.e.
udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

udp_port_tuple = (host, udp_port)
udp_socket.sendto(data_str, udp_port_tuple)

**Comment by gusutabopb** [comment]
Unfortunately, aioinflux does not support UDP at the moment and I have no plans to add such support.

Aiohttp (main aioinflux dependency) currently only supports a TCP and Unix sockets, so adding UDP support to aioinflux would be a quite complex task. See the [aiohttp docs](http://docs.aiohttp.org/en/stable/client_reference.html?highlight=tcpconnector#connectors) for more details.

**Comment by Sovetnikov** [comment]
pip install asyncudp

```
import asyncudp
from aioinflux import InfluxDBClient, serialization

class InfluxDBClientUDP(InfluxDBClient):
    def __init__(self, *args, udp_port=None, **kwargs):
        super().__init__(*args, **kwargs)
        print(udp_port)
        self.udp_port = int(udp_port) if udp_port else None
        self._udp_sock = None

    async def write_udp(
            self,
            data,
            measurement=None,
            tag_columns=None,
            **extra_tags,
    ):
        data = serialization.serialize(data, measurement, tag_columns, **extra_tags)
        if self._udp_sock is None:
            self._udp_sock = await asyncudp.create_socket(remote_addr=(self.host, self.udp_port))
        self._udp_sock.sendto(data)
```
