### ISSUE TITLE
Support querying multiple measurements/series

### ISSUE THREAD

**Issue by miracle2k** [plugaai/aioinflux#6]
Currently, when querying multiple series with `chunked=True`, there is no way to know which series a data point belongs to; the interface only provides the point and does not pass along the name of the measurement.

I fixed this for myself here: https://github.com/plugaai/aioinflux/compare/master...miracle2k:multiseries?expand=1 but it's not a clean pull request because it depends on my changes to make the library run on Python 3.5 (for PyPy).

**Comment by gusutabopb** [comment]
Thanks for raising the issue!

I thought quite a lot about this and decided to totally drop built-in parsing for chunked responses in [v0.2.0](https://github.com/plugaai/aioinflux/releases/tag/v0.2.0), so this issue doesn't apply anymore.

With the new iteration mechanism (`iter_resp`), users can customize point parsing as they prefer (for both chunked and non-chunked responses). It should allow for querying with multiple statements/series/measurements as long as you write an appropriate parser.

Things should now be more consistent (across chunked/non-chunked responses), more flexible (with the use of custom parsers) and easier to use (simple iteration via `iter_resp`).
