### ISSUE TITLE
Support for trio/curio

### ISSUE THREAD

**Issue by miracle2k** [plugaai/aioinflux#8]
Would you be open to adding support for trio (https://github.com/python-trio/trio) and curio (https://github.com/dabeaz/curio) as alt event loops?

This would mostly require supporting an optional non-aiohttp backend for the http calls.

**Comment by gusutabopb** [comment]
Aioinflux is tightly coupled with aiohttp (which is tightly coupled with asyncio), so unless aiohttp adds support to alternative async frameworks such as curio/trio, aioinflux won't support anything else besides stdlib asyncio.

Alternative event loops (e.g. uvloop) can be used though.
